[package]
name = "protoc-rust-caper"
version = "0.1.0"
authors = ["AprliRainkun <zmy.2347@sjtu.edu.cn>"]

[dependencies]
Inflector = "0.11"
protoc = "1.4"
protoc-rust = "1.4"
protobuf = {version = "1.4", features = ["with-bytes"]}
quote = "0.3"
tempdir = "0.3"
