sudo: false

language: rust

cache: 
  directories:
    - $HOME/protobuf
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

matrix:
  include:
    - env: PROTOBUF_VERSION=3.5.1 INSTALL_PATH="$HOME/protobuf/v$PROTOBUF_VERSION"
      rust: stable

before_install:
  - sudo apt-get install autoconf automake libtool curl make g++ unzip
  - ./install_protoc.sh
  - PATH=$INSTALL_PATH/bin:$PATH protoc --version

script:
  - rustc --version
  - PATH=$INSTALL_PATH/bin:$PATH cargo run --manifest-path=copra-compile/Cargo.toml
  - PATH=$INSTALL_PATH/bin:$PATH
  - cargo build --all
